name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/mateki0/projects/1
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          labeled: bug, needs-triage
          label-operator: OR
